-- MySQL Script generated by MySQL Workbench
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FO R_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- ----------------------------------------------------- 
-- Schema mydb
-- ----------------------------------------------------- 
DROP SCHEMA IF EXISTS `mydb` ;
 -- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ; 
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Клиент`
-- -----------------------------------------------------


DROP TABLE IF EXISTS `mydb`.`Клиент` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Клиент` (
`idКлиент` INT NOT NULL,
`ФИО_клиента` VARCHAR(45) NOT NULL, 
`Номер_телефона` DECIMAL(11) NULL, 
PRIMARY KEY (`idКлиент`))
ENGINE = InnoDB;

-- ----------------------------------------------------- 
-- Table `mydb`.`Заказ`
-- ----------------------------------------------------- 
DROP TABLE IF EXISTS `mydb`.`Заказ` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Заказ` ( 
`Номер_заказа` INT NOT NULL, 
`Дата_оформления` DATETIME NOT NULL, 
`Дата_выполнения` DATETIME NULL, 
`Клиент_idКлиент` INT NOT NULL,
PRIMARY KEY (`Номер_заказа`),
INDEX `fk_Заказ_Клиент_idx` (`Клиент_idКлиент` ASC) VISIBLE, 
CONSTRAINT `fk_Заказ_Клиент`
FOREIGN KEY (`Клиент_idКлиент`) 
REFERENCES `mydb`.`Клиент` (`idКлиент`) 
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Работник`
-- ----------------------------------------------------- 
DROP TABLE IF EXISTS `mydb`.`Работник` ;
CREATE TABLE IF NOT EXISTS `mydb`.`Работник` ( 
`idРаботник` INT NOT NULL,
`ФИО_работника` VARCHAR(45) NOT NULL, 
`Должность` VARCHAR(45) NULL,
PRIMARY KEY (`idРаботник`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Изделие`
-- ----------------------------------------------------- 
DROP TABLE IF EXISTS `mydb`.`Изделие` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Изделие` ( 
`idИзделие` INT NOT NULL,
`Название_изделия` VARCHAR(45) NOT NULL, 
`Цена` DECIMAL(8,2) NOT NULL, 
`Количество_изделий` INT NULL, 
`Заказ_Номер_заказа` INT NOT NULL, 
`Работник_idРаботник` INT NOT NULL,
PRIMARY KEY (`idИзделие`, `Работник_idРаботник`, `Заказ_Номер_заказа`), 
INDEX `fk_Изделие_Заказ1_idx` (`Заказ_Номер_заказа` ASC) VISIBLE, 
INDEX `fk_Изделие_Работник1_idx` (`Работник_idРаботник` ASC) VISIBLE, 
CONSTRAINT `fk_Изделие_Заказ1`
FOREIGN KEY (`Заказ_Номер_заказа`) 
REFERENCES `mydb`.`Заказ` (`Номер_заказа`) ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_Изделие_Работник1` FOREIGN KEY (`Работник_idРаботник`) REFERENCES `mydb`.`Работник` (`idРаботник`) ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- ----------------------------------------------------- 
-- Table `mydb`.`Склад`
-- ----------------------------------------------------- 

DROP TABLE IF EXISTS `mydb`.`Склад` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Склад` ( 
`idСклад` INT NOT NULL,
`Адрес_склада` VARCHAR(60) NULL,
PRIMARY KEY (`idСклад`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Поставщик`
-- -----------------------------------------------------


DROP TABLE IF EXISTS `mydb`.`Поставщик` ; 
CREATE TABLE IF NOT EXISTS `mydb`.`Поставщик` (
`idПоставщик` INT NOT NULL, 
`Название_поставщика` VARCHAR(45) NOT NULL, 
PRIMARY KEY (`idПоставщик`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Фурнитура`
-- ----------------------------------------------------- 
DROP TABLE IF EXISTS `mydb`.`Фурнитура` ;
CREATE TABLE IF NOT EXISTS `mydb`.`Фурнитура` ( 
`idФурнитуры` INT NOT NULL,
`Название_фурнитуры` VARCHAR(45) NOT NULL,
`Единица_измерения` VARCHAR(45) NOT NULL,
`Поставщик_idПоставщик` INT NOT NULL,
INDEX `fk_Фурнитура_Поставщик1_idx` (`Поставщик_idПоставщик` ASC) VISIBLE, 
INDEX `fk_Фурнитура_Склад1_idx` (`idФурнитуры` ASC) VISIBLE,
PRIMARY KEY (`idФурнитуры`), 
CONSTRAINT `fk_Фурнитура_Поставщик1`
FOREIGN KEY (`Поставщик_idПоставщик`) 
REFERENCES `mydb`.`Поставщик` (`idПоставщик`) ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_Фурнитура_Склад1` 
FOREIGN KEY (`idФурнитуры`) REFERENCES `mydb`.`Склад` (`idСклад`) 
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Фурнитура_изделия`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `mydb`.`Фурнитура_изделия` ;
CREATE TABLE IF NOT EXISTS `mydb`.`Фурнитура_изделия` ( 
`Фурнитура_idФурнитуры` INT NOT NULL,
`Количество` INT NOT NULL,
`Работник_idРаботник` INT NOT NULL,
`Склад_idСклад` INT NOT NULL,
`Изделие_idИзделие` INT NOT NULL,
PRIMARY KEY (`Фурнитура_idФурнитуры`, `Изделие_idИзделие`, `Работник_idРаботник`), 
INDEX `fk_Фурнитура_изделия_Работник1_idx` (`Работник_idРаботник` ASC) VISIBLE, 
INDEX `fk_Фурнитура_изделия_Склад1_idx` (`Склад_idСклад` ASC) VISIBLE,
INDEX `fk_Фурнитура_изделия_Фурнитура1_idx` (`Фурнитура_idФурнитуры` ASC) VISIBLE, 
INDEX `fk_Фурнитура_изделия_Изделие1_idx` (`Изделие_idИзделие` ASC) VISIBLE, 
CONSTRAINT `fk_Фурнитура_изделия_Работник1`
FOREIGN KEY (`Работник_idРаботник`) 
REFERENCES `mydb`.`Работник` (`idРаботник`) 
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_Фурнитура_изделия_Склад1` 
FOREIGN KEY (`Склад_idСклад`) 
REFERENCES `mydb`.`Склад` (`idСклад`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_Фурнитура_изделия_Фурнитура1`
FOREIGN KEY (`Фурнитура_idФурнитуры`) 
REFERENCES `mydb`.`Фурнитура` (`idФурнитуры`) 
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_Фурнитура_изделия_Изделие1` 
FOREIGN KEY (`Изделие_idИзделие`) 
REFERENCES `mydb`.`Изделие` (`idИзделие`) 
ON DELETE NO ACTION
ON UPDATE NO ACTION) 
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Поставка`
-- ----------------------------------------------------- 
DROP TABLE IF EXISTS `mydb`.`Поставка` ;
CREATE TABLE IF NOT EXISTS `mydb`.`Поставка` ( 
`idПоставка` INT NOT NULL,
`Дата_поставки` DATETIME NOT NULL, 
`Склад_idСклад` INT NOT NULL, 
`Поставщик_idПоставщик` INT NOT NULL, 
PRIMARY KEY (`idПоставка`),
INDEX `fk_Поставка_Склад1_idx` (`Склад_idСклад` ASC) VISIBLE,
INDEX `fk_Поставка_Поставщик1_idx` (`Поставщик_idПоставщик` ASC) VISIBLE, 
CONSTRAINT `fk_Поставка_Склад1`
FOREIGN KEY (`Склад_idСклад`) 
REFERENCES `mydb`.`Склад` (`idСклад`) 
ON DELETE NO ACTION
ON UPDATE NO ACTION, 
CONSTRAINT `fk_Поставка_Поставщик1`
FOREIGN KEY (`Поставщик_idПоставщик`) 
REFERENCES `mydb`.`Поставщик` (`idПоставщик`) 
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
